version: '3.8'

services:
  ms3_api:
    build: .
    container_name: ms3_api_standalone
    ports:
      - "8003:8003"
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ms3_test_db
      - MS3_S3_ENDPOINT=http://minio:9000
    depends_on:
      - redis
      - db
      - minio
    volumes:
      - ms3_shared_media:/srv/ms3_reports/media
    networks:
      - ms3_test_net

  ms3_worker:
    build: .
    container_name: ms3_worker_standalone
    command: ["celery", "-A", "infrastructure.celery_app:celery_app", "worker", "--loglevel=info", "-Q", "reports_queue"]
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ms3_test_db
      - MS3_S3_ENDPOINT=http://minio:9000
    depends_on:
      - redis
      - db
      - minio
    volumes:
      - ms3_shared_media:/srv/ms3_reports/media
    networks:
      - ms3_test_net

  redis:
    image: redis:7-alpine
    container_name: ms3_redis_test
    networks:
      - ms3_test_net

  db:
    image: pgvector/pgvector:pg16
    container_name: ms3_db_test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ms3_test_db
    networks:
      - ms3_test_net

  minio:
    image: minio/minio:latest
    container_name: ms3_minio_test
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - ms3_test_net

networks:
  ms3_test_net:
    driver: bridge

volumes:
  ms3_shared_media: