# =============================================================================
# Copyright (C) 2024-2026 Mole.AI — All Rights Reserved.
#
# AVISO DE PROPIEDAD INTELECTUAL:
# Este archivo es propiedad exclusiva de Mole.AI y sus autores originales.
# Queda estrictamente prohibida la copia, modificación, distribución,
# sublicenciamiento o uso comercial de este código, total o parcialmente,
# sin la autorización expresa y por escrito de los titulares del Copyright.
#
# Cualquier uso no autorizado será perseguido conforme a la Ley Federal
# del Derecho de Autor (México) y tratados internacionales aplicables.
# =============================================================================
"""
Django settings for mole_ai_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Importar configuración de paths dinámica
try:
    from .path_config import *  # Importa todo de path_config.py
except ImportError:
    print("⚠️  path_config.py no encontrado. Usando configuración por defecto.")
    # Fallback: agregar carpeta apps manualmente
    APPS_DIR = BASE_DIR / 'apps'
    if str(APPS_DIR) not in sys.path:
        sys.path.insert(0, str(APPS_DIR))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# ── Security Hardening (M3) ─────────────────────────────────────────────────
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'

def _split_env_list(var_name, default=None):
    raw = os.getenv(var_name)
    if raw is None:
        return [x.strip() for x in (default or '').split(',') if x.strip()]
    return [x.strip() for x in raw.split(',') if x.strip()]


# Hosts allowed to serve the application (read from env, default localhost)
ALLOWED_HOSTS = _split_env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1')

# Application definition
INSTALLED_APPS = [
    # Django Channels debe ir PRIMERO para ASGI
    'channels',  # WebSocket support - CRITICAL: must be first
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'storages',
    'pgvector',
    'axes',  # M3/M4: brute-force protection
    'core',
    'ai_models',
    'authentication',
    'plants',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # CRITICAL: after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',  # M3/M4: brute-force lockout
]

ROOT_URLCONF = 'mole_ai_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ASGI Application for Channels
ASGI_APPLICATION = 'mole_ai_backend.asgi.application'

# Database - Supabase PostgreSQL for production, SQLite for development
if DEBUG:
    # Development with SQLite (no external dependencies)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    print("🛠️ Using SQLite for development (DEBUG=True)")
else:
    # Production with Supabase PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('SUPABASE_DB_NAME'),
            'USER': os.getenv('SUPABASE_DB_USER'),
            'PASSWORD': os.getenv('SUPABASE_DB_PASSWORD'),
            'HOST': os.getenv('SUPABASE_DB_HOST'),
            'PORT': os.getenv('SUPABASE_DB_PORT', '6543'),  # M4: Transaction Pooler
            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }
    print("🚀 Using Supabase PostgreSQL for production (DEBUG=False)")

# Password validation - Disabled for Supabase auth
AUTH_PASSWORD_VALIDATORS = []

# ── M5: Argon2 Password Hashing ────────────────────────────────────────────
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]

# ── M4: django-axes brute-force protection ─────────────────────────────────
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]
AXES_FAILURE_LIMIT = int(os.getenv('AXES_FAILURE_LIMIT', '5'))
AXES_COOLOFF_TIME = 1  # hours
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']

# Custom user model — activated Sprint 2
AUTH_USER_MODEL = 'authentication.User'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'authentication.infrastructure.authentication.SupabaseAuthentication',
        'authentication.infrastructure.authentication.HardwareAPIKeyAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
     'DEFAULT_THROTTLE_CLASSES': [
         'rest_framework.throttling.AnonRateThrottle',
         'rest_framework.throttling.UserRateThrottle'
     ],
     'DEFAULT_THROTTLE_RATES': {
         'anon': '100/hour',
         'user': '1000/hour',
         'llm_chat': '60/minute',
         'diagnostics': '30/minute',
         'sensor_data': '200/minute'
     }
}

# CORS settings - Configuración completa para frontend
# CORS configuration can be provided via env var `CORS_ALLOWED_ORIGINS` as comma-separated list
# Example: CORS_ALLOWED_ORIGINS=https://example.com,https://your-domain.com
env_cors = _split_env_list('CORS_ALLOWED_ORIGINS')
if env_cors:
    CORS_ALLOWED_ORIGINS = env_cors
else:
    # sensible defaults for local development
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:8080",
        "http://127.0.0.1:8080",
        "http://localhost:5500",
        "http://127.0.0.1:5500",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "file://",
    ]

# Allow all origins when DEBUG is enabled (development convenience)
CORS_ALLOW_CREDENTIALS = True
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False

# Headers permitidos para autenticación y contenido
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Métodos HTTP permitidos
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Exponer headers específicos al frontend
CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrftoken',
]

# CSRF trusted origins via env var (comma separated). Hosting providers require full https://domain
csrf_env = _split_env_list('CSRF_TRUSTED_ORIGINS')
if csrf_env:
    # Ensure entries are full URLs
    CSRF_TRUSTED_ORIGINS = [u if u.startswith('http') else f'https://{u}' for u in csrf_env]
else:
    CSRF_TRUSTED_ORIGINS = [f'https://{h}' for h in ALLOWED_HOSTS if h and h != '127.0.0.1' and h != 'localhost']

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# WhiteNoise configuration for static files
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_MAX_AGE = 0 if DEBUG else 31557600  # 1 year in production
WHITENOISE_SKIP_COMPRESS_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'gz', 'tgz', 'bz2', 'tbz', 'xz']

# Media files - Supabase S3
MEDIA_URL = '/media/'
MEDIA_ROOT = 'media/'

# Django Storages for Supabase S3
if os.getenv('SUPABASE_S3_BUCKET'):
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_ACCESS_KEY_ID = os.getenv('SUPABASE_S3_ACCESS_KEY')
    AWS_SECRET_ACCESS_KEY = os.getenv('SUPABASE_S3_SECRET_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('SUPABASE_S3_BUCKET')
    AWS_S3_ENDPOINT_URL = os.getenv('SUPABASE_S3_ENDPOINT')
    AWS_S3_REGION_NAME = os.getenv('SUPABASE_S3_REGION', 'us-east-1')
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False

# Supabase JWT Settings
SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_JWT_SECRET = os.getenv('SUPABASE_JWT_SECRET')
SUPABASE_JWT_ALGORITHM = os.getenv('SUPABASE_JWT_ALGORITHM', 'HS256')

# Hugging Face Configuration
HUGGINGFACE_API_KEY = os.getenv('HUGGINGFACE_API_KEY')
HF_MODEL_NAME = os.getenv('HF_MODEL_NAME', 'deepseek-ai/DeepSeek-R1-Distill-Qwen-7B')
HF_INFERENCE_API_URL = os.getenv('HF_INFERENCE_API_URL', 'https://api-inference.huggingface.co/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B')
HF_API_TIMEOUT = int(os.getenv('HF_API_TIMEOUT', '30'))
HF_MAX_RETRIES = int(os.getenv('HF_MAX_RETRIES', '3'))

# DeepSeek Ecosystem — model identifiers (must match .env)
VISION_MODEL_NAME = os.getenv('VISION_MODEL_NAME', 'deepseek-ai/deepseek-vl2-tiny')
EMBEDDING_MODEL_ID = os.getenv('EMBEDDING_MODEL_ID', 'BAAI/bge-small-en-v1.5')
LLM_MODEL_ID = os.getenv('LLM_MODEL_ID', 'deepseek-ai/DeepSeek-R1-Distill-Qwen-7B')

# pgvector settings
PGVECTOR_AUTO_INSTALL = True

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'ai_models': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# Cache configuration for django-ratelimit - Redis for production
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'mole_ai',
        'TIMEOUT': 300,
    }
}

# Create cache directory
os.makedirs(BASE_DIR / 'cache', exist_ok=True)

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Channels Configuration for WebSocket support
ASGI_APPLICATION = 'mole_ai_backend.asgi.application'

# CHANNEL_LAYERS: Use Redis in production when REDIS_URL is provided,
# otherwise fallback to InMemoryChannelLayer for local development.
# REDIS_URL already defined above in CACHES section
if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }

# Mole-AI Service Configuration
# Configure Mole-AI (FastAPI) service URL. In Render we'll set FASTAPI_URL env var to point to the FastAPI service.
MOLE_AI_SERVICE_URL = os.environ.get('FASTAPI_URL')
MOLE_AI_TIMEOUT = int(os.getenv('MOLE_AI_TIMEOUT', '120'))
MOLE_AI_API_KEY = os.environ.get('MOLE_AI_API_KEY')

# ── Fail-fast: critical inter-service variables ────────────────────────────
_missing_vars = []
if not MOLE_AI_SERVICE_URL:
    _missing_vars.append('FASTAPI_URL')
if not MOLE_AI_API_KEY:
    _missing_vars.append('MOLE_AI_API_KEY')
if _missing_vars and not DEBUG:
    raise RuntimeError(
        f"❌ Variables de entorno obligatorias no configuradas: {', '.join(_missing_vars)}. "
        "El servidor no puede arrancar de forma segura sin la comunicación inter-servicio."
    )
elif _missing_vars:
    import warnings
    warnings.warn(
        f"⚠️ Variables inter-servicio faltantes: {', '.join(_missing_vars)}. "
        "Las llamadas al microservicio de IA fallarán."
    )

# Hardware IoT Authentication (Machine-to-Machine)
# API Key for IoT devices (ESP32, Raspberry Pi, etc.) to authenticate when sending telemetry
# This is a static key that devices use in place of JWT tokens (which are for human users)
HARDWARE_API_KEY = os.getenv('HARDWARE_API_KEY')
if not HARDWARE_API_KEY:
    import warnings
    warnings.warn('HARDWARE_API_KEY not set. IoT authentication will fail.')
    HARDWARE_API_KEY = ''

import mimetypes
mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("application/javascript", ".js", True)