"""
Custom authentication class for Local HS256 JWT tokens.
Validates JWT tokens generated by the local login_view (HS256).
"""
from rest_framework import authentication, exceptions
from django.conf import settings
import jwt
from django.contrib.auth import get_user_model
import logging

logger = logging.getLogger(__name__)

class LocalJWTAuthentication(authentication.BaseAuthentication):
    """
    Custom authentication class for Local HS256 JWT tokens.
    Validates JWT tokens generated by login_view (HS256 with JWT_SECRET_KEY).
    """
    
    def authenticate(self, request):
        """
        Authenticate the request and return a two-tuple of (user, token).
        """
        auth_header = authentication.get_authorization_header(request).split()
        
        if not auth_header or auth_header[0].lower() != b'bearer':
            return None
            
        if len(auth_header) == 1:
            raise exceptions.AuthenticationFailed(
                'Invalid bearer header. No credentials provided.'
            )
        elif len(auth_header) > 2:
            raise exceptions.AuthenticationFailed(
                'Invalid bearer header. Token string should not contain spaces.'
            )
        
        try:
            token = auth_header[1].decode('utf-8')
        except UnicodeError:
            raise exceptions.AuthenticationFailed(
                'Invalid token header. Token string should not contain invalid characters.'
            )
        
        return self._authenticate_credentials(request, token)
    
    def _authenticate_credentials(self, request, token: str):
        """
        Authenticate the token with local HS256 and return user.
        """
        payload = None
        User = get_user_model()
        
        try:
            # Use JWT_SECRET_KEY (local auth) or fallback to SECRET_KEY
            local_key = getattr(settings, 'JWT_SECRET_KEY', None) or settings.SECRET_KEY
            
            # Decode with HS256
            payload = jwt.decode(
                token,
                local_key,
                algorithms=['HS256'],
                audience=getattr(settings, 'JWT_AUDIENCE', 'authenticated'),
                options={'verify_exp': True, 'verify_aud': True},
                leeway=getattr(settings, 'JWT_LEEWAY', 30),
            )
            
        except jwt.ExpiredSignatureError:
            logger.warning("Expired token: %s", token[:10] + '...')
            raise exceptions.AuthenticationFailed('Token has expired.')
        except (jwt.InvalidTokenError, jwt.DecodeError) as e:
            logger.error("Invalid token: %s - %s", token[:10] + '...', str(e))
            raise exceptions.AuthenticationFailed('Invalid token.')
        except Exception as e:
            logger.exception("Unexpected error during token validation: %s", str(e))
            raise exceptions.AuthenticationFailed(f'Token validation error: {str(e)}')
        
        if not payload:
            raise exceptions.AuthenticationFailed('Token validation failed.')
        
        # Get user from payload
        username = payload.get('username')
        if not username:
            raise exceptions.AuthenticationFailed('Invalid token: missing username.')
        
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            logger.error("User not found for token: %s", username)
            raise exceptions.AuthenticationFailed('User not found.')
        
        if not user.is_active:
            raise exceptions.AuthenticationFailed('User is inactive.')
        
        # Attach JWT payload to user for use in views
        user.jwt_payload = payload
        
        return (user, token)
    
    def authenticate_header(self, request):
        return 'Bearer realm="api"'
