# Generated by Django 4.2.29 on 2026-03-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorlog',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('light', 'Light Intensity'), ('soil_moisture', 'Soil Moisture'), ('ph', 'pH Level'), ('nutrients', 'Nutrient Levels'), ('uv', 'UV Index'), ('soil_temperature', 'Soil Temperature'), ('pH_cnn', 'pH CNN Inference')], db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='sensorlog',
            unique_together={('device_id', 'sensor_type', 'timestamp')},
        ),
    ]
