# Generated by Django 4.2.29 on 2026-03-08 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sensorlog_sensor_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorlog',
            options={'managed': False, 'ordering': ['-recorded_at']},
        ),
    ]
