# Generated by Django 4.2.29 on 2026-03-16 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_sensorlog_hardware_sync'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sensorlog',
            name='sensor_logs_device__a5cbe0_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensorlog',
            name='sensor_logs_plant_i_8c76b4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='sensorlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='air_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='light_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='soil_humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='uv_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticogeolocalizado',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbackticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='plant_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.RemoveField(
            model_name='sensorlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sensorlog',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='sensorlog',
            name='location_x',
        ),
        migrations.RemoveField(
            model_name='sensorlog',
            name='location_y',
        ),
        migrations.RemoveField(
            model_name='sensorlog',
            name='location_z',
        ),
        migrations.RemoveField(
            model_name='sensorlog',
            name='sensor_type',
        ),
        migrations.RemoveField(
            model_name='sensorlog',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='sensorlog',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='sensorlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sensorlog',
            name='value',
        ),
    ]
