# Generated by Django 4.2.29 on 2026-04-26 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0003_add_nom059_protection_and_favorite_plant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(db_index=True, help_text='Full S3 key including prefix, e.g. images/<uuid>.zip', max_length=512, unique=True)),
                ('s3_bucket', models.CharField(default='mole-training-data', max_length=128)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('file_size', models.PositiveBigIntegerField(help_text='File size in bytes')),
                ('checksum_sha256', models.CharField(blank=True, help_text='SHA-256 hex digest for integrity verification', max_length=64)),
                ('disease_label', models.CharField(blank=True, help_text='Disease or condition label, e.g. "roya", "tizón tardío"', max_length=100)),
                ('severity', models.CharField(choices=[('healthy', 'Sana'), ('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10)),
                ('geo_location', models.JSONField(blank=True, default=dict, help_text='Capture coordinates: {"lat": float, "lon": float}')),
                ('description', models.TextField(blank=True, help_text='Additional notes about the image or dataset')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de subida'), ('UPLOADING', 'Subiendo a S3'), ('UPLOADED', 'Almacenado en S3'), ('INDEXING', 'Procesando en microservicio'), ('INDEXED', 'Indexado / Procesado exitosamente'), ('FAILED', 'Fallido')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('species', models.ForeignKey(blank=True, help_text='Plant species depicted in the image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_images', to='plants.speciescatalog')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Image',
                'verbose_name_plural': 'Training Images',
                'db_table': 'training_images',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['species', 'disease_label'], name='training_im_species_e8f5de_idx'), models.Index(fields=['status', 'created_at'], name='training_im_status_18ad07_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(db_index=True, help_text='Full S3 key including prefix, e.g. documents/<uuid>.pdf', max_length=512, unique=True)),
                ('s3_bucket', models.CharField(default='mole-training-data', max_length=128)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='application/pdf', max_length=100)),
                ('file_size', models.PositiveBigIntegerField(help_text='File size in bytes')),
                ('checksum_sha256', models.CharField(blank=True, help_text='SHA-256 hex digest for integrity verification', max_length=64)),
                ('category', models.CharField(choices=[('phytopathology', 'Fitopatología'), ('nutrition', 'Nutrición Vegetal'), ('agronomy', 'Agronomía General'), ('pest_control', 'Control de Plagas'), ('soil_science', 'Edafología'), ('regulations', 'Normatividad (NOM/SAGARPA)'), ('other', 'Otro')], default='other', max_length=30)),
                ('language', models.CharField(default='es', max_length=5)),
                ('description', models.TextField(blank=True, help_text='Brief description of document contents for catalog purposes')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de subida'), ('UPLOADING', 'Subiendo a S3'), ('UPLOADED', 'Almacenado en S3'), ('INDEXING', 'Procesando en microservicio'), ('INDEXED', 'Indexado / Procesado exitosamente'), ('FAILED', 'Fallido')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Document',
                'verbose_name_plural': 'Training Documents',
                'db_table': 'training_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='training_do_status_d0ae41_idx'), models.Index(fields=['category', 'status'], name='training_do_categor_0802a1_idx')],
            },
        ),
    ]
