# Generated by Django 4.2.30 on 2026-09-27 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_models', '0003_alter_cnninference_user_alter_llmrequest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PvuRouteLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('route', models.CharField(choices=[('local', 'Local'), ('cloud', 'Cloud'), ('hybrid', 'Hybrid')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=30)),
                ('net', models.CharField(blank=True, max_length=10)),
                ('battery_pct', models.FloatField(blank=True, null=True)),
                ('wifi_rssi', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pvu_route_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
