# Generated by Django 4.2.29 on 2026-03-17 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from pgvector.django import VectorExtension
import uuid


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_alter_sensorlog_sensor_type_and_more'), ('core', '0003_wide_table_sensor_logs'), ('core', '0004_diagnosticos_geolocalizados'), ('core', '0005_botanicalknowledge_feedbackticket_and_more'), ('core', '0006_sensorlog_hardware_sync'), ('core', '0007_remove_sensorlog_sensor_logs_device__a5cbe0_idx_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── Paso 0: Activar la extensión pgvector en PostgreSQL ──────────────
        # VectorExtension() es idempotente (equivale a CREATE EXTENSION IF NOT EXISTS vector).
        # Debe ser la PRIMERA operación para que los VectorField() de las
        # operaciones siguientes puedan referenciarse al tipo 'vector' de PG.
        VectorExtension(),
        migrations.CreateModel(
            name='AIDiagnostic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plant_id', models.UUIDField(db_index=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('diagnosis_label', models.TextField(blank=True, null=True)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_diagnostics',
                'ordering': ['-analyzed_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BotanicalKnowledge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('chunk_metadata', models.JSONField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
            ],
            options={
                'db_table': 'botanical_knowledge',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoGeolocalizado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('condition_name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnostic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geolocations', to='core.aidiagnostic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagnosticos_geolocalizados',
                'managed': True,
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(choices=[('bug', 'Bug'), ('suggestion', 'Suggestion'), ('ai_error', 'AI Error'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_tickets',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plant_id', models.UUIDField(db_index=True)),
                ('ph_level', models.FloatField(blank=True, null=True)),
                ('air_humidity', models.FloatField(blank=True, null=True)),
                ('air_temperature', models.FloatField(blank=True, null=True)),
                ('light_level', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('soil_humidity', models.FloatField(blank=True, null=True)),
                ('uv_index', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sensor_logs',
                'ordering': ['-recorded_at'],
                'managed': True,
                'indexes': [],
            },
        ),
    ]
