# Generated by Django 4.2.29 on 2026-03-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_canonical_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorlog',
            name='air_temperature',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='ph_level',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='soil_humidity',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='uv_index',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='sensorlog',
            index=models.Index(fields=['plant_id', 'recorded_at'], name='sensor_logs_plant_i_1b9910_idx'),
        ),
    ]
