# Generated by Django 4.2.29 on 2026-03-21 22:32

from django.db import migrations


def create_view(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        sql = """
        CREATE MATERIALIZED VIEW admin_stats AS
        SELECT 1 as id, 
               AVG(soil_humidity) as avg_hum, 
               AVG(air_temperature) as avg_temp, 
               AVG(ph_level) as avg_ph, 
               AVG(uv_index) as avg_uv 
        FROM sensor_logs;
        """
        schema_editor.execute(sql)
        sql_index = "CREATE UNIQUE INDEX admin_stats_id_idx ON admin_stats (id);"
        schema_editor.execute(sql_index)
    else:
        sql = """
        CREATE VIEW admin_stats AS
        SELECT 1 as id, 
               AVG(soil_humidity) as avg_hum, 
               AVG(air_temperature) as avg_temp, 
               AVG(ph_level) as avg_ph, 
               AVG(uv_index) as avg_uv 
        FROM sensor_logs;
        """
        schema_editor.execute(sql)

def drop_view(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("DROP MATERIALIZED VIEW IF EXISTS admin_stats;")
    else:
        schema_editor.execute("DROP VIEW IF EXISTS admin_stats;")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sensorlog_air_temperature_and_more'),
    ]

    operations = [
        migrations.RunPython(create_view, reverse_code=drop_view)
    ]
