# Generated by Django 4.2.30 on 2026-05-10 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_aidiagnostic_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('method', models.CharField(choices=[('wifi', 'Wi‑Fi'), ('bluetooth', 'Bluetooth')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iot_nodes',
                'ordering': ['-created_at'],
            },
        ),
    ]
