# Generated by Django 4.2.30 on 2026-05-19 05:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_iotnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('auth_token', models.CharField(help_text='Bearer token', max_length=128, unique=True)),
                ('status', models.CharField(default='offline', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hardware_pin', models.CharField(help_text="Ej: '32', 'A0'", max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='core.device')),
            ],
            options={
                'unique_together': {('device', 'hardware_pin')},
            },
        ),
        migrations.CreateModel(
            name='SoilReading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('soil_humidity', models.FloatField()),
                ('ph_level', models.FloatField(blank=True, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_readings', to='core.plant')),
            ],
        ),
        migrations.CreateModel(
            name='AmbientReading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('air_temperature', models.FloatField(blank=True, null=True)),
                ('air_humidity', models.FloatField(blank=True, null=True)),
                ('light_level', models.FloatField(blank=True, null=True)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambient_readings', to='core.device')),
            ],
        ),
    ]
