# Generated by Django 4.2.30 on 2026-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_divice_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of last telemetry frame received (heartbeat)', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('warning', 'Warning'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
