# Generated by Django 4.2.30 on 2026-05-20 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_speciescatalog_category'),
        ('core', '0008_device_last_seen_alter_device_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareBinding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hardware_pin', models.CharField(help_text="Ej: '32', 'A0'", max_length=10)),
            ],
            options={
                'db_table': 'hardware_bindings',
            },
        ),
        migrations.CreateModel(
            name='HourlyAmbientAggregate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hour', models.DateTimeField(db_index=True)),
                ('avg_air_temperature', models.FloatField(null=True)),
                ('avg_air_humidity', models.FloatField(null=True)),
                ('avg_uv_index', models.FloatField(null=True)),
                ('avg_light_level', models.FloatField(null=True)),
                ('sample_count', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'hourly_ambient_aggregates',
                'ordering': ['-hour'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HourlySoilAggregate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hour', models.DateTimeField(db_index=True, help_text='Truncated to hour')),
                ('avg_soil_humidity', models.FloatField()),
                ('min_soil_humidity', models.FloatField()),
                ('max_soil_humidity', models.FloatField()),
                ('sample_count', models.PositiveIntegerField()),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_soil', to='core.hardwarebinding')),
            ],
            options={
                'db_table': 'hourly_soil_aggregates',
                'ordering': ['-hour'],
                'managed': True,
                'unique_together': {('binding', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='TelemetryArchive',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('s3_key', models.CharField(max_length=512, unique=True)),
                ('rows_archived', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'telemetry_archives',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='soilreading',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.RemoveField(
            model_name='soilreading',
            name='plant',
        ),
        migrations.AddField(
            model_name='device',
            name='report_interval_minutes',
            field=models.PositiveSmallIntegerField(default=5, help_text='Cadencia de reporte en minutos (1-120). Usado por Celery para calcular umbrales de liveness.'),
        ),
        migrations.AlterModelTable(
            name='device',
            table='devices',
        ),
        migrations.AlterModelTable(
            name='soilreading',
            table='soil_readings',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.AddField(
            model_name='telemetryarchive',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='core.device'),
        ),
        migrations.AddField(
            model_name='hourlyambientaggregate',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_ambient', to='core.device'),
        ),
        migrations.AddField(
            model_name='hardwarebinding',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='core.device'),
        ),
        migrations.AddField(
            model_name='hardwarebinding',
            name='plant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_binding', to='plants.userplant'),
        ),
        migrations.AddField(
            model_name='soilreading',
            name='binding',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soil_readings', to='core.hardwarebinding'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='hourlyambientaggregate',
            unique_together={('device', 'hour')},
        ),
        migrations.AlterUniqueTogether(
            name='hardwarebinding',
            unique_together={('device', 'hardware_pin')},
        ),
    ]
