# Generated by Django 4.2.30 on 2026-09-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hardwarebinding_hourlyambientaggregate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='auth_token_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Expiración del Bearer token; NULL = sin expiración (legacy)', null=True),
        ),
    ]
