# Generated by Django 4.2.30 on 2026-09-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_botanico_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidiagnostic',
            name='pvu_reason',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
