# Generated by Django 4.2.29 on 2026-03-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_consent',
            field=models.BooleanField(default=False, help_text='El usuario ha otorgado consentimiento explícito para el tratamiento de sus datos personales (LFPDPPP Art. 8).'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_consent_date',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se otorgó el consentimiento.', null=True),
        ),
    ]
