# Generated by Django 4.2.30 on 2026-09-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_email_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, help_text='Marca de tiempo del último envío de recuperación.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, help_text='Hash del token de recuperación (un solo uso).', max_length=64, null=True),
        ),
    ]
