# Generated by Django 5.2.7 on 2026-02-22 05:02

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnostic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plant_id', models.CharField(db_index=True, max_length=100)),
                ('diagnostic_type', models.CharField(choices=[('disease', 'Disease Detection'), ('nutrient_deficiency', 'Nutrient Deficiency'), ('pest_infestation', 'Pest Infestation'), ('environmental_stress', 'Environmental Stress'), ('growth_analysis', 'Growth Analysis')], max_length=30)),
                ('condition_name', models.CharField(max_length=200)),
                ('condition_description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('ai_model_used', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('processing_time_ms', models.IntegerField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('sensor_data_reference', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('treatment_protocol', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_diagnostics',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantKnowledge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('knowledge_type', models.CharField(choices=[('care_guide', 'Care Guide'), ('disease_info', 'Disease Information'), ('treatment', 'Treatment Protocol'), ('growth_stage', 'Growth Stage Info'), ('environmental', 'Environmental Requirements')], db_index=True, max_length=20)),
                ('plant_species', models.CharField(db_index=True, max_length=100)),
                ('plant_genus', models.CharField(db_index=True, max_length=50)),
                ('plant_family', models.CharField(db_index=True, max_length=50)),
                ('common_names', models.JSONField(blank=True, default=list)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plant_knowledge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('light', 'Light Intensity'), ('soil_moisture', 'Soil Moisture'), ('ph', 'pH Level'), ('nutrients', 'Nutrient Levels')], db_index=True, max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('plant_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('location_x', models.FloatField(blank=True, null=True)),
                ('location_y', models.FloatField(blank=True, null=True)),
                ('location_z', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sensor_logs',
                'ordering': ['-timestamp'],
                'managed': True,
                'indexes': [models.Index(fields=['device_id', 'timestamp'], name='sensor_logs_device__a5cbe0_idx'), models.Index(fields=['plant_id', 'sensor_type', 'timestamp'], name='sensor_logs_plant_i_8c76b4_idx')],
            },
        ),
    ]
