# Generated by Django 4.2.29 on 2026-03-15 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_diagnosticos_geolocalizados'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotanicalKnowledge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('chunk_metadata', models.JSONField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
            ],
            options={
                'db_table': 'botanical_knowledge',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FeedbackTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(choices=[('bug', 'Bug'), ('suggestion', 'Suggestion'), ('ai_error', 'AI Error'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_tickets',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='PlantKnowledge',
        ),
        migrations.AlterModelOptions(
            name='aidiagnostic',
            options={'managed': True, 'ordering': ['-analyzed_at']},
        ),
        migrations.AlterModelOptions(
            name='diagnosticogeolocalizado',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sensorlog',
            options={'managed': True, 'ordering': ['-recorded_at']},
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='ai_model_used',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='condition_description',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='condition_name',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='diagnostic_type',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='follow_up_days',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='follow_up_required',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='processing_time_ms',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='resolution_notes',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='sensor_data_reference',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='status',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='treatment_protocol',
        ),
        migrations.RemoveField(
            model_name='aidiagnostic',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='aidiagnostic',
            name='analyzed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aidiagnostic',
            name='diagnosis_label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aidiagnostic',
            name='image_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aidiagnostic',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aidiagnostic',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aidiagnostic',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aidiagnostic',
            name='plant_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
