[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags = 
    -I include

# Instalación automática de drivers para los sensores I2C
lib_deps =
    robtillaart/DHT20 @ ^0.3.1
    adafruit/Adafruit LTR390 Library @ ^1.1.2