# Generated by Django 4.2.29 on 2026-03-16 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scientific_name', models.TextField()),
                ('common_name', models.TextField(blank=True, null=True)),
                ('ideal_humidity_min', models.FloatField(blank=True, null=True)),
                ('ideal_humidity_max', models.FloatField(blank=True, null=True)),
                ('ideal_temp_min', models.FloatField(blank=True, null=True)),
                ('ideal_temp_max', models.FloatField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('ideal_ph_min', models.FloatField(blank=True, null=True)),
                ('ideal_ph_max', models.FloatField(blank=True, null=True)),
                ('ideal_ph_optimal', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'species_catalog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(blank=True, db_column='species_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.speciescatalog')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_plants',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
