# Generated by Django 4.2.30 on 2026-04-23 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0002_speciescatalog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciescatalog',
            name='is_protected_nom059',
            field=models.BooleanField(default=False, help_text='Indica si la especie está protegida por NOM-059-SEMARNAT.'),
        ),
        migrations.AddField(
            model_name='speciescatalog',
            name='protection_category',
            field=models.CharField(blank=True, choices=[('P', 'En peligro de extinción'), ('T', 'Amenazada'), ('Pr', 'Sujeta a protección especial')], max_length=20),
        ),
        migrations.CreateModel(
            name='FavoritePlant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='plants.userplant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_plants',
                'managed': True,
                'unique_together': {('user', 'plant')},
            },
        ),
    ]
