# Generated by Django 4.2.30 on 2026-05-11 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0003_add_nom059_protection_and_favorite_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciescatalog',
            name='category',
            field=models.CharField(choices=[('planta', 'Planta'), ('plaga', 'Plaga'), ('enfermedad', 'Enfermedad')], default='planta', max_length=20),
        ),
        migrations.CreateModel(
            name='Flora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(help_text='Nombre común', max_length=128)),
                ('scientific_name', models.CharField(help_text='Nombre científico', max_length=256)),
                ('family', models.CharField(blank=True, help_text='Familia taxonómica', max_length=128)),
                ('treatment', models.TextField(blank=True, help_text='Método de tratamiento o control')),
                ('image', models.ImageField(blank=True, null=True, upload_to='flora_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flora',
                'ordering': ['-created_at'],
            },
        ),
    ]
