# Generated by Django 4.2.30 on 2026-05-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_speciescatalog_category_flora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciescatalog',
            name='category',
            field=models.CharField(choices=[('planta', 'Planta'), ('plaga', 'Plaga'), ('enfermedad', 'Enfermedad')], db_index=True, default='planta', help_text='Categoría taxonómica para filtrado en la Wiki.', max_length=20),
        ),
    ]
