# Generated by Django 4.2.30 on 2026-05-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_speciescatalog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciescatalog',
            name='habitat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciescatalog',
            name='irrigation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciescatalog',
            name='soil_humidity_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciescatalog',
            name='soil_humidity_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciescatalog',
            name='soil_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciescatalog',
            name='uses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciescatalog',
            name='uv_rays',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
