# Generated by Django 4.2 on 2026-05-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_speciescatalog_habitat_speciescatalog_irrigation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='hardware_pin',
            field=models.CharField(blank=True, help_text='Pin físico del sensor en el nodo ESP32', max_length=10, null=True),
        ),
    ]
