# Generated by Django 4.2.30 on 2026-09-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_userplant_hardware_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciescatalog',
            name='is_endemic',
            field=models.BooleanField(db_index=True, default=False, help_text='Endémica de México (portal público, issue 18).'),
        ),
    ]
