# Generated by Django 5.2.7 on 2026-02-09 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelConfiguration",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=50, unique=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("llm", "Large Language Model"),
                            ("cnn", "Convolutional Neural Network"),
                            ("transformer", "Transformer Model"),
                            ("custom", "Custom Model"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_version", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("parameters", models.JSONField(default=dict)),
                ("default_settings", models.JSONField(default=dict)),
                ("min_memory_mb", models.IntegerField()),
                ("recommended_memory_mb", models.IntegerField()),
                ("gpu_required", models.BooleanField(default=False)),
                ("gpu_memory_mb", models.IntegerField(blank=True, null=True)),
                ("endpoint_url", models.URLField(blank=True)),
                ("api_key_required", models.BooleanField(default=False)),
                ("rate_limit_per_minute", models.IntegerField(default=60)),
                ("is_active", models.BooleanField(default=True)),
                ("is_production_ready", models.BooleanField(default=False)),
                ("health_check_url", models.URLField(blank=True)),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ai_model_configurations",
                "ordering": ["model_name"],
                "indexes": [
                    models.Index(
                        fields=["model_type", "is_active"],
                        name="ai_model_co_model_t_9e11e2_idx",
                    ),
                    models.Index(
                        fields=["is_production_ready"],
                        name="ai_model_co_is_prod_9968b5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelPerformance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=50)),
                (
                    "model_category",
                    models.CharField(
                        choices=[
                            ("llm", "Large Language Model"),
                            ("cnn", "Convolutional Neural Network"),
                            ("transformer", "Transformer Model"),
                            ("ensemble", "Ensemble Model"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_version", models.CharField(max_length=20)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("precision", models.FloatField(blank=True, null=True)),
                ("recall", models.FloatField(blank=True, null=True)),
                ("f1_score", models.FloatField(blank=True, null=True)),
                ("auc_score", models.FloatField(blank=True, null=True)),
                ("avg_response_time_ms", models.FloatField()),
                ("p95_response_time_ms", models.FloatField()),
                ("p99_response_time_ms", models.FloatField()),
                ("avg_memory_usage_mb", models.FloatField()),
                ("peak_memory_usage_mb", models.FloatField()),
                ("cpu_usage_percent", models.FloatField()),
                ("total_requests", models.IntegerField(default=0)),
                ("successful_requests", models.IntegerField(default=0)),
                ("failed_requests", models.IntegerField(default=0)),
                ("metrics_date", models.DateField()),
                ("metrics_hour", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "model_performance",
                "ordering": ["-metrics_date", "-metrics_hour"],
                "indexes": [
                    models.Index(
                        fields=["model_category", "metrics_date"],
                        name="model_perfo_model_c_f682b5_idx",
                    ),
                    models.Index(
                        fields=["model_name", "metrics_date"],
                        name="model_perfo_model_n_bb9637_idx",
                    ),
                ],
                "unique_together": {
                    ("model_name", "model_version", "metrics_date", "metrics_hour")
                },
            },
        ),
        migrations.CreateModel(
            name="CNNInference",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("request_id", models.CharField(db_index=True, max_length=100)),
                ("image_url", models.URLField()),
                ("image_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("disease_detection", "Disease Detection"),
                            ("plant_identification", "Plant Identification"),
                            ("pest_detection", "Pest Detection"),
                            ("nutrient_deficiency", "Nutrient Deficiency"),
                            ("growth_stage", "Growth Stage Analysis"),
                        ],
                        max_length=30,
                    ),
                ),
                ("model_name", models.CharField(max_length=50)),
                ("model_version", models.CharField(max_length=20)),
                ("image_size", models.JSONField(default=dict)),
                ("preprocessing_steps", models.JSONField(blank=True, default=list)),
                ("predictions", models.JSONField(default=list)),
                ("confidence_scores", models.JSONField(default=list)),
                ("top_prediction", models.JSONField(default=dict)),
                ("features_vector", models.TextField(blank=True, null=True)),
                ("embedding_vector", models.TextField(blank=True, null=True)),
                ("inference_time_ms", models.IntegerField()),
                ("memory_usage_mb", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("human_verified", models.BooleanField(default=False)),
                ("human_prediction", models.JSONField(blank=True, default=dict)),
                ("verification_accuracy", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cnn_inferences",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="cnn_inferen_user_id_8acf8f_idx",
                    ),
                    models.Index(
                        fields=["model_type", "status"],
                        name="cnn_inferen_model_t_fd21ba_idx",
                    ),
                    models.Index(
                        fields=["request_id"], name="cnn_inferen_request_73ac4b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LLMRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("plant_care_advice", "Plant Care Advice"),
                            ("diagnostic_explanation", "Diagnostic Explanation"),
                            ("treatment_recommendation", "Treatment Recommendation"),
                            ("knowledge_query", "Knowledge Query"),
                            ("chat_conversation", "Chat Conversation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("prompt", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                ("model_name", models.CharField(max_length=50)),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=1000)),
                ("response", models.TextField(blank=True)),
                ("response_metadata", models.JSONField(blank=True, default=dict)),
                ("token_usage", models.JSONField(blank=True, default=dict)),
                ("processing_time_ms", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("user_rating", models.IntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "llm_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="llm_request_user_id_1e8c1d_idx",
                    ),
                    models.Index(
                        fields=["session_id", "created_at"],
                        name="llm_request_session_d2439f_idx",
                    ),
                    models.Index(
                        fields=["request_type", "status"],
                        name="llm_request_request_847ab6_idx",
                    ),
                ],
            },
        ),
    ]
