# =============================================================================
# Copyright (C) 2024-2026 Mole.AI — All Rights Reserved.
# =============================================================================
"""
Django settings for mole_ai_backend project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
import sys
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# 1. Configuración de Base y Entorno
load_dotenv()
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from .path_config import *
except ImportError:
    APPS_DIR = BASE_DIR / 'apps'
    if str(APPS_DIR) not in sys.path:
        sys.path.insert(0, str(APPS_DIR))

SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# Fail-fast checks for production environment: ensure critical secrets present
if not DEBUG:
    
    required_in_prod = ['SECRET_KEY', 'HARDWARE_API_KEY']
    missing = [v for v in required_in_prod if not os.getenv(v)]
    if not _env_first('JWT_SECRET_KEY', 'IDP_JWT_SECRET', 'SUPABASE_JWT_SECRET'):
        missing.append('JWT_SECRET_KEY')
    # database requirement: accept either DB_URL (DSN libpq) or classic part set
    db_ok = bool(_env_first('DB_URL', 'DATABASE_URL')) or (
        _env_first('DB_NAME', 'POSTGRES_DB')
        and _env_first('DB_PASSWORD', 'POSTGRES_PASSWORD')
        and _env_first('DB_HOST', 'POSTGRES_HOST')
    )
    if not db_ok:
        missing.append('DB_URL or DB_NAME/DB_PASSWORD/DB_HOST')
    if missing:
        raise ImproperlyConfigured('Missing required environment variables for production: ' + ', '.join(missing))

# 2. Seguridad Hardening
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'

# Confiar en la cabecera de Nginx (Terminación SSL en ALB o Nginx)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

def _split_env_list(var_name, default=None):
    raw = os.getenv(var_name)
    if raw is None:
        return [x.strip() for x in (default or '').split(',') if x.strip()]
    return [x.strip() for x in raw.split(',') if x.strip()]


def _env_first(*names, default=None):
    """Primera variable de entorno definida y no vacía.

    Convención .env genérica: el nombre canónico va primero y los legados
    (AWS_*, SUPABASE_*, POSTGRES_*, USE_S3…) después, como fallback de
    transición. No asumir: vacío cuenta como ausente.
    """
    for name in names:
        value = os.getenv(name)
        if value:
            return value
    return default

# Lista de hosts internos necesarios para healthchecks y proxy reverso
INTERNAL_HOSTS = ['localhost', '127.0.0.1', 'django-backend']

# Leer de entorno y combinar con los hosts internos (usando set para evitar duplicados)
env_hosts = _split_env_list('DJANGO_ALLOWED_HOSTS', default='') + _split_env_list('ALLOWED_HOSTS', default='')
ALLOWED_HOSTS = list(set(env_hosts + INTERNAL_HOSTS))

# 3. Definición de Aplicaciones
INSTALLED_APPS = [
    'channels',  # WebSocket support
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'storages',
    'pgvector',
    'axes',  
    'drf_spectacular',
    'apps.core',
    'apps.ai_models',
    'apps.authentication',
    'apps.plants',
    'apps.training_data',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.authentication.middleware.JwtHttpMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
    'mole_ai_backend.middleware.error_handling.GracefulDegradationMiddleware',
]

ROOT_URLCONF = 'mole_ai_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'mole_ai_backend.asgi.application'

# 4. Bases de Datos
# Fuente: DB_URL (DSN libpq, prioridad) o partes DB_* (genéricas, fallback POSTGRES_*).
# Sin ninguna → SQLite local (solo desarrollo).
def _resolve_db_url():
    dsn = _env_first('DB_URL', 'DATABASE_URL')
    if dsn:
        return dsn
    name = _env_first('DB_NAME', 'POSTGRES_DB')
    if name:
        from urllib.parse import quote as _quote
        user = _env_first('DB_USER', 'POSTGRES_USER', default='mole')
        password = _env_first('DB_PASSWORD', 'POSTGRES_PASSWORD', default='')
        host = _env_first('DB_HOST', 'POSTGRES_HOST', default='localhost')
        port = _env_first('DB_PORT', 'POSTGRES_PORT', default='5432')
        return f"postgresql://{user}:{_quote(password, safe='')}@{host}:{port}/{name}"
    return f"sqlite:///{BASE_DIR / 'db.sqlite3'}"


if DEBUG:
    # En desarrollo local: DSN/partes o SQLite si no hay nada definido
    DATABASES = {
        'default': dj_database_url.config(
            default=_resolve_db_url(),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # En producción (Docker/local): exige DSN o partes (ver fail-fast arriba)
    DATABASES = {
        'default': dj_database_url.config(
            default=_resolve_db_url(),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }

# 5. Autenticación y Modelos de Usuario
AUTH_USER_MODEL = 'authentication.User'
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'apps.authentication.backends.DualLoginBackend',
]
AXES_FAILURE_LIMIT = int(os.getenv('AXES_FAILURE_LIMIT', '5'))
AXES_COOLOFF_TIME = 1
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']

# 6. Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'apps.authentication.infrastructure.authentication.SupabaseAuthentication',  # Disabled for login, use in specific views
        'apps.authentication.infrastructure.authentication.HardwareAPIKeyAuthentication',
        'apps.authentication.infrastructure.local_jwt_auth.LocalJWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    # Contrato móvil (issue 11): listas DRF paginadas, PAGE_SIZE 50.
    # Solo afecta a vistas con ListModelMixin (hoy: SpeciesViewSet);
    # las vistas función con Response manual no cambian.
    # Web tolerante: main.js acepta array o envelope {results}.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '10000/minute',
        'llm_chat': '60/minute',
        'diagnostics': '30/minute',
        'sensor_data': '200/minute'
    }
}

# 7. Configuración de JWT Local (CRÍTICO PARA EVITAR 401)
JWT_SECRET_KEY = _env_first('JWT_SECRET_KEY', 'IDP_JWT_SECRET', 'SUPABASE_JWT_SECRET')  # Fallback for migration
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')
JWT_AUDIENCE = 'authenticated'
JWT_LEEWAY = 30

# Token lifetime in minutes (default 20)
JWT_TTL_MINUTES = int(os.getenv('JWT_TTL_MINUTES', '20'))

# 8. CORS & CSRF
# NOTE: Nginx handles CORS completely. This section is kept for reference only.
# All CORS headers are added in nginx.conf for /api/* endpoints.
# Keep CORS_ALLOWED_ORIGINS empty to avoid duplication.
CORS_ALLOW_CREDENTIALS = False
CORS_ALLOWED_ORIGINS = []  # Nginx handles CORS completely
CORS_ALLOW_HEADERS = []  # No custom headers needed
CORS_ALLOW_METHODS = []  # No custom methods needed

csrf_env = _split_env_list('CSRF_TRUSTED_ORIGINS')
if csrf_env:
    CSRF_TRUSTED_ORIGINS = [u if u.startswith('http') else f'https://{u}' for u in csrf_env]
else:
    CSRF_TRUSTED_ORIGINS = [f'https://{h}' for h in ALLOWED_HOSTS if h and h not in ('127.0.0.1', 'localhost')]

# 9. Internacionalización y Archivos
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = 'media/'

# ── Object Storage (API S3v4 vía boto3: MinIO/S3/Garage compatibles) ─────────
# OBJECT_STORAGE_ENABLED=True  → django-storages S3Boto3 backend
# OBJECT_STORAGE_ENABLED=False → local filesystem (MEDIA_ROOT)
# Nombres de ATRIBUTO AWS_* los exige django-storages; solo cambia la FUENTE env.
OBJECT_STORAGE_ENABLED = _env_first('OBJECT_STORAGE_ENABLED', 'USE_S3', default='True').lower() == 'true'
USE_S3 = OBJECT_STORAGE_ENABLED  # alias legacy

if USE_S3:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    # Credenciales: genéricas → AWS_* legacy → MINIO_ROOT_* (compose E2E/dev)
    AWS_ACCESS_KEY_ID = _env_first('OBJECT_STORAGE_ACCESS_KEY', 'AWS_ACCESS_KEY_ID', 'MINIO_ROOT_USER')
    AWS_SECRET_ACCESS_KEY = _env_first('OBJECT_STORAGE_SECRET_KEY', 'AWS_SECRET_ACCESS_KEY', 'MINIO_ROOT_PASSWORD')
    AWS_STORAGE_BUCKET_NAME = _env_first('OBJECT_STORAGE_BUCKET_MEDIA', 'AWS_STORAGE_BUCKET_NAME', default='mole-training-data')
    AWS_S3_ENDPOINT_URL = _env_first('OBJECT_STORAGE_ENDPOINT_URL', 'AWS_S3_ENDPOINT_URL') or None  # None → endpoint nativo del proveedor
    AWS_S3_REGION_NAME = _env_first('OBJECT_STORAGE_REGION', 'AWS_S3_REGION_NAME', default='us-east-1')
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = 'private'
    AWS_QUERYSTRING_AUTH = True  # Presigned URLs siempre autenticadas
    AWS_S3_ADDRESSING_STYLE = 'path'  # Requerido para MinIO

# Training data bucket (compartido por documents/ e images/)
TRAINING_BUCKET_NAME = _env_first('OBJECT_STORAGE_BUCKET_TRAINING', 'TRAINING_BUCKET_NAME', default='mole-training-data')
TRAINING_MAX_PDF_SIZE = 50 * 1024 * 1024   # 50 MB
TRAINING_MAX_IMAGE_SIZE = 200 * 1024 * 1024  # 200 MB
TRAINING_PRESIGNED_TTL = 900  # 15 minutos

# 10. IA & Inter-Service (Mole-AI)
# Proveedores: NVIDIA NIM (LLM/visión/embeddings) + OpenWeather (clima).
# HuggingFace retirado 2026-09-14 (ADR-0004): sin claves ni defaults HF.
# B2/C1 FIX: Default explícito al container_name real; genérico AI_SERVICE_URL
# primero, legacy 'FASTAPI_URL' después.
MOLE_AI_SERVICE_URL = _env_first('AI_SERVICE_URL', 'FASTAPI_URL', default='http://ms2_chat:8002')
MOLE_AI_TIMEOUT = int(os.getenv('MOLE_AI_TIMEOUT', '120'))
# X-API-Key gateway↔MS: genérico EDGE_API_KEY primero, legacy después.
MOLE_AI_API_KEY = _env_first('EDGE_API_KEY', 'MOLE_AI_API_KEY', default='')
# C3 FIX: Sin default vacío — si no está definida, la autenticación IoT falla silenciosamente
HARDWARE_API_KEY = os.getenv('HARDWARE_API_KEY', '')

# 11. Redis & Celery
REDIS_URL = os.getenv('REDIS_URL', 'redis://redis:6379/0')
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient'},
        'KEY_PREFIX': 'mole_ai',
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [REDIS_URL]},
    }
}

from celery.schedules import crontab

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/1')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://redis:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CELERY_BEAT_SCHEDULE = {
    'cleanup-temp-files-every-day': {
        'task': 'cleanup_temp_files',
        'schedule': 86400.0,
    },
    'check-device-liveness-every-minute': {
        'task': 'check_device_liveness',
        'schedule': 60.0,
    },
    'dlm-pipeline-daily-0300-utc': {
        'task': 'dlm_pipeline',
        'schedule': crontab(hour=3, minute=0),
    },
}

# 12. Logging con PII Filter
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'pii_filter': {
            '()': 'apps.authentication.infrastructure.logging_filters.PIIFilter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name} — {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} — {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'filters': ['pii_filter'],
        },
        'file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': '/tmp/mole_ai.log',
            'when': 'midnight',
            'interval': 1,
            'backupCount': 15,  # Retención de 15 días
            'encoding': 'utf-8',
            'formatter': 'verbose',
            'filters': ['pii_filter'],
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'apps.authentication': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.plants': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# 15. Observabilidad B6: Sentry opcional (sin DSN = no-op).
# Sin PII: el PIIFilter ya redacta logs; Sentry solo recibe tracebacks.
# DSN vía env/secret manager, jamás commiteado.
_SENTRY_DSN = os.getenv('SENTRY_DSN', '')
if _SENTRY_DSN:
    try:
        import sentry_sdk

        sentry_sdk.init(
            dsn=_SENTRY_DSN,
            send_default_pii=False,
            traces_sample_rate=0.1,
        )
    except Exception:
        pass

import mimetypes

mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("application/javascript", ".js", True)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SPECTACULAR_SETTINGS = {
    'TITLE': 'Mole.AI API',
    'VERSION': '1.0.0',
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
}

# --- ENRUTAMIENTO AISLADO DE CELERY ---
CELERY_TASK_ROUTES = {
    # Tareas de limpieza se quedan en Django (cola por defecto)
    'apps.ai_models.tasks.cleanup_temp_files': {'queue': 'celery'},
    'apps.core.tasks.refresh_admin_stats_task': {'queue': 'celery'},
    'apps.core.tasks.check_device_liveness': {'queue': 'celery'},
    
    # Tareas de Visión (MS1) - Asignamos a una cola dedicada
    'apps.ai_models.tasks.analyze_vision_async': {'queue': 'vision_queue'},
    'apps.ai_models.tasks.train_vision_async': {'queue': 'vision_queue'},
    
    # Tareas de Reportes y MLOps (MS3) - Asignamos a una cola dedicada
    'apps.core.tasks.generate_master_report_task': {'queue': 'reports_queue'},
    'apps.core.tasks.generate_pdf_async': {'queue': 'reports_queue'},
    
    # Tareas de Training Data Pipeline (Fase 3 - MLOps)
    'apps.training_data.tasks.notify_training_asset': {'queue': 'training_queue'},
    'apps.training_data.tasks.update_training_status': {'queue': 'training_queue'},

    # Chat RAG async (Fase 2 - cola dedicada para aislar latencia LLM)
    'apps.core.tasks.chat_async': {'queue': 'chat_queue'},
}

WHITENOISE_MANIFEST_STRICT = False
