# =============================================================================
# Copyright (C) 2024-2026 Mole.AI — All Rights Reserved.
# =============================================================================
"""
Django settings for mole_ai_backend project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
import dj_database_url

# 1. Configuración de Base y Entorno
load_dotenv()
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from .path_config import *
except ImportError:
    APPS_DIR = BASE_DIR / 'apps'
    if str(APPS_DIR) not in sys.path:
        sys.path.insert(0, str(APPS_DIR))

SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# Fail-fast checks for production environment: ensure critical secrets present
if not DEBUG:
    
    required_in_prod = ['SECRET_KEY', 'JWT_SECRET_KEY', 'HARDWARE_API_KEY']
    missing = [v for v in required_in_prod if not os.getenv(v)]
    # database requirement: accept either DATABASE_URL or classic POSTGRES_* set
    db_ok = bool(os.getenv('DATABASE_URL')) or (
        os.getenv('POSTGRES_DB') and os.getenv('POSTGRES_PASSWORD') and os.getenv('POSTGRES_HOST')
    )
    if not db_ok:
        missing.append('DATABASE_URL or SUPABASE_DB_*')
    if missing:
        raise ImproperlyConfigured('Missing required environment variables for production: ' + ', '.join(missing))

# 2. Seguridad Hardening
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'

def _split_env_list(var_name, default=None):
    raw = os.getenv(var_name)
    if raw is None:
        return [x.strip() for x in (default or '').split(',') if x.strip()]
    return [x.strip() for x in raw.split(',') if x.strip()]

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'django-backend']

# 3. Definición de Aplicaciones
INSTALLED_APPS = [
    'channels',  # WebSocket support
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'storages',
    'pgvector',
    'axes',  
    'drf_spectacular',
    'apps.core',
    'apps.ai_models',
    'apps.authentication',
    'apps.plants',
    'apps.training_data',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.authentication.middleware.JwtHttpMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
    'mole_ai_backend.middleware.error_handling.GracefulDegradationMiddleware',
]

ROOT_URLCONF = 'mole_ai_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'mole_ai_backend.asgi.application'

# 4. Bases de Datos
if DEBUG:
    # En desarrollo local: usamos SQLite o DATABASE_URL si está disponible
    DATABASES = {
        'default': dj_database_url.config(
            default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # En producción (Docker/Supabase): exigimos DATABASE_URL con fallback local seguro
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL', f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }

# 5. Autenticación y Modelos de Usuario
AUTH_USER_MODEL = 'authentication.User'
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'apps.authentication.backends.DualLoginBackend',
]
AXES_FAILURE_LIMIT = int(os.getenv('AXES_FAILURE_LIMIT', '5'))
AXES_COOLOFF_TIME = 1
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']

# 6. Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'apps.authentication.infrastructure.authentication.SupabaseAuthentication',  # Disabled for login, use in specific views
        'apps.authentication.infrastructure.authentication.HardwareAPIKeyAuthentication',
        'apps.authentication.infrastructure.local_jwt_auth.LocalJWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '10000/minute',
        'llm_chat': '60/minute',
        'diagnostics': '30/minute',
        'sensor_data': '200/minute'
    }
}

# 7. Configuración de JWT Local (CRÍTICO PARA EVITAR 401)
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY') or os.getenv('SUPABASE_JWT_SECRET')  # Fallback for migration
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')
JWT_AUDIENCE = 'authenticated'
JWT_LEEWAY = 30

# 8. CORS & CSRF
# NOTE: Nginx handles CORS completely. This section is kept for reference only.
# All CORS headers are added in nginx.conf for /api/* endpoints.
# Keep CORS_ALLOWED_ORIGINS empty to avoid duplication.
CORS_ALLOW_CREDENTIALS = False
CORS_ALLOWED_ORIGINS = []  # Nginx handles CORS completely
CORS_ALLOW_HEADERS = []  # No custom headers needed
CORS_ALLOW_METHODS = []  # No custom methods needed

csrf_env = _split_env_list('CSRF_TRUSTED_ORIGINS')
if csrf_env:
    CSRF_TRUSTED_ORIGINS = [u if u.startswith('http') else f'https://{u}' for u in csrf_env]
else:
    CSRF_TRUSTED_ORIGINS = [f'https://{h}' for h in ALLOWED_HOSTS if h and h not in ('127.0.0.1', 'localhost')]

# 9. Internacionalización y Archivos
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = 'media/'

# ── Object Storage (MinIO local / AWS S3 producción) ──────────────────────
# USE_S3=True  → django-storages S3Boto3 backend (MinIO o AWS)
# USE_S3=False → local filesystem (MEDIA_ROOT)
USE_S3 = os.getenv('USE_S3', 'True').lower() == 'true'

if USE_S3:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    # En dev/Docker: fallback a MINIO_ROOT_USER/PASSWORD
    # En producción AWS: usar AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY directas
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', os.getenv('MINIO_ROOT_USER'))
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', os.getenv('MINIO_ROOT_PASSWORD'))
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', 'mole-training-data')
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL') or None  # None → boto3 uses native AWS S3 endpoint
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = 'private'
    AWS_QUERYSTRING_AUTH = True  # Presigned URLs siempre autenticadas
    AWS_S3_ADDRESSING_STYLE = 'path'  # Requerido para MinIO

# Training data bucket (compartido por documents/ e images/)
TRAINING_BUCKET_NAME = os.getenv('TRAINING_BUCKET_NAME', 'mole-training-data')
TRAINING_MAX_PDF_SIZE = 50 * 1024 * 1024   # 50 MB
TRAINING_MAX_IMAGE_SIZE = 200 * 1024 * 1024  # 200 MB
TRAINING_PRESIGNED_TTL = 900  # 15 minutos

# 10. IA & Inter-Service (Mole-AI)
HUGGINGFACE_API_KEY = os.getenv('HUGGINGFACE_API_KEY')
# B2/C1 FIX: Default explícito al container_name real; variable legacy 'FASTAPI_URL' como override
MOLE_AI_SERVICE_URL = os.getenv('FASTAPI_URL', 'http://ms2_chat:8002')
MOLE_AI_TIMEOUT = int(os.getenv('MOLE_AI_TIMEOUT', '120'))
MOLE_AI_API_KEY = os.getenv('MOLE_AI_API_KEY')
# C3 FIX: Sin default vacío — si no está definida, la autenticación IoT falla silenciosamente
HARDWARE_API_KEY = os.getenv('HARDWARE_API_KEY', '')

VISION_MODEL_NAME = os.getenv('VISION_MODEL_NAME', 'deepseek-ai/deepseek-vl2-tiny')
EMBEDDING_MODEL_ID = os.getenv('EMBEDDING_MODEL_ID', 'BAAI/bge-small-en-v1.5')
LLM_MODEL_ID = os.getenv('LLM_MODEL_ID', 'deepseek-ai/DeepSeek-R1-Distill-Qwen-7B')

# 11. Redis & Celery
REDIS_URL = os.getenv('REDIS_URL', 'redis://redis:6379/0')
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient'},
        'KEY_PREFIX': 'mole_ai',
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [REDIS_URL]},
    }
}

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/1')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://redis:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CELERY_BEAT_SCHEDULE = {
    'cleanup-temp-files-every-day': {
        'task': 'cleanup_temp_files',
        'schedule': 86400.0,
    },
}

# 12. Logging con PII Filter
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'pii_filter': {
            '()': 'apps.authentication.infrastructure.logging_filters.PIIFilter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name} — {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} — {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'filters': ['pii_filter'],
        },
        'file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'mole_ai.log',
            'when': 'midnight',
            'interval': 1,
            'backupCount': 15,  # Retención de 15 días
            'encoding': 'utf-8',
            'formatter': 'verbose',
            'filters': ['pii_filter'],
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'apps.authentication': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.plants': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

import mimetypes
mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("application/javascript", ".js", True)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SPECTACULAR_SETTINGS = {
    'TITLE': 'Mole.AI API',
    'VERSION': '1.0.0',
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
}

# --- ENRUTAMIENTO AISLADO DE CELERY ---
CELERY_TASK_ROUTES = {
    # Tareas de limpieza se quedan en Django (cola por defecto)
    'apps.ai_models.tasks.cleanup_temp_files': {'queue': 'celery'},
    'apps.core.tasks.refresh_admin_stats_task': {'queue': 'celery'},
    
    # Tareas de Visión (MS1) - Asignamos a una cola dedicada
    'apps.ai_models.tasks.analyze_vision_async': {'queue': 'vision_queue'},
    'apps.ai_models.tasks.train_vision_async': {'queue': 'vision_queue'},
    
    # Tareas de Reportes y MLOps (MS3) - Asignamos a una cola dedicada
    'apps.core.tasks.generate_master_report_task': {'queue': 'reports_queue'},
    'apps.core.tasks.generate_pdf_async': {'queue': 'reports_queue'},
    
    # Tareas de Training Data Pipeline (Fase 3 - MLOps)
    'apps.training_data.tasks.notify_training_asset': {'queue': 'training_queue'},
    'apps.training_data.tasks.update_training_status': {'queue': 'training_queue'},

    # Chat RAG async (Fase 2 - cola dedicada para aislar latencia LLM)
    'apps.core.tasks.chat_async': {'queue': 'chat_queue'},
}

WHITENOISE_MANIFEST_STRICT = False
